# Generated by Django 4.0.4 on 2022-05-04 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterField(
            model_name='flight',
            name='delay',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='class_type',
            field=models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('F', 'First')], max_length=50),
        ),
    ]
