# Generated by Django 4.0.4 on 2022-05-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_payment_options_alter_flight_delay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasclass',
            old_name='aircraft_model',
            new_name='aircraft',
        ),
        migrations.RenameField(
            model_name='hasclass',
            old_name='class_id',
            new_name='class_info',
        ),
    ]
