# Generated by Django 4.0.4 on 2022-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_rename_aircraft_model_hasclass_aircraft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('GIZ', 'Gizan'), ('DMM', 'Dammam')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source_city',
            field=models.CharField(choices=[('GIZ', 'Gizan'), ('DMM', 'Dammam')], max_length=50),
        ),
    ]
