# Generated by Django 4.0.4 on 2022-05-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_alter_flight_destination_alter_flight_source_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('GIZ', 'Gizan'), ('DMM', 'Dammam'), ('Abha', 'AHB'), ('Al-Baha', 'ABT'), ('Alahsa', 'HOF'), ('Arar', 'RAE'), ('Bisha', 'BHH'), ('Dammam', 'DMM'), ('Dawadmi', 'DWD'), ('Dhahran', 'DHA'), ('Gassim', 'ELQ'), ('Gurayat', 'URY'), ('Hafr Albatin', 'HBT'), ('Hail', 'HAS'), ('Jazan', 'GIZ'), ('Jeddah', 'JED'), ('Jouf', 'AJF'), ('Khamis Mushait', 'KMX'), ('Majma', 'MJH'), ('Nejran', 'EAM'), ('Qaisumah', 'AQI'), ('Rafha', 'RAH'), ('Riyadh', 'RUH'), ('Sharurah', 'SHW'), ('Sulayel', 'SLF'), ('Tabuk', 'TUU'), ('Taif', 'TIF'), ('Turaif', 'TUI'), ('Unayzah', 'UZH'), ('Wadi Ad Dawasir', 'WAE'), ('Wedjh', 'EJH'), ('Yanbu', 'YNB'), ('Zilfi', 'ZUL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source_city',
            field=models.CharField(choices=[('GIZ', 'Gizan'), ('DMM', 'Dammam'), ('Abha', 'AHB'), ('Al-Baha', 'ABT'), ('Alahsa', 'HOF'), ('Arar', 'RAE'), ('Bisha', 'BHH'), ('Dammam', 'DMM'), ('Dawadmi', 'DWD'), ('Dhahran', 'DHA'), ('Gassim', 'ELQ'), ('Gurayat', 'URY'), ('Hafr Albatin', 'HBT'), ('Hail', 'HAS'), ('Jazan', 'GIZ'), ('Jeddah', 'JED'), ('Jouf', 'AJF'), ('Khamis Mushait', 'KMX'), ('Majma', 'MJH'), ('Nejran', 'EAM'), ('Qaisumah', 'AQI'), ('Rafha', 'RAH'), ('Riyadh', 'RUH'), ('Sharurah', 'SHW'), ('Sulayel', 'SLF'), ('Tabuk', 'TUU'), ('Taif', 'TIF'), ('Turaif', 'TUI'), ('Unayzah', 'UZH'), ('Wadi Ad Dawasir', 'WAE'), ('Wedjh', 'EJH'), ('Yanbu', 'YNB'), ('Zilfi', 'ZUL')], max_length=50),
        ),
    ]
