# Generated by Django 4.0.4 on 2022-05-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_flight_destination_alter_flight_source_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='a', max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
