# Generated by Django 4.0.4 on 2022-05-09 08:46

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_flight_destination_alter_flight_source_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('seat_number'), django.db.models.expressions.F('flight'), name='ticket_constraint'),
        ),
    ]
