cities = [
    ('GIZ', 'Gizan'),
    ('DMM', 'Dammam'),
    ('Abha', 'AHB'),
    ('Al-Baha', 'ABT'),
    ('Alahsa', 'HOF'),
    ('Arar', 'RAE'),
    ('Bisha', 'BHH'),
    ('Dammam', 'DMM'),
    ('Dawadmi', 'DWD'),
    ('Dhahran', 'DHA'),
    ('Gassim', 'ELQ'),
    ('Gurayat', 'URY'),
    ('Hafr Albatin', 'HBT'),
    ('Hail', 'HAS'),
    ('Jazan', 'GIZ'),
    ('Jeddah', 'JED'),
    ('Jouf', 'AJF'),
    ('Khamis Mushait', 'KMX'),
    ('Majma', 'MJH'),
    ('Nejran', 'EAM'),
    ('Qaisumah', 'AQI'),
    ('Rafha', 'RAH'),
    ('Riyadh', 'RUH'),
    ('Sharurah', 'SHW'),
    ('Sulayel', 'SLF'),
    ('Tabuk', 'TUU'),
    ('Taif', 'TIF'),
    ('Turaif', 'TUI'),
    ('Unayzah', 'UZH'),
    ('Wadi Ad Dawasir', 'WAE'),
    ('Wedjh', 'EJH'),
    ('Yanbu', 'YNB'),
    ('Zilfi', 'ZUL'),
]