cities = [
    ('GIZ', 'Gizan'),
    ('AHB', 'Abha'),
    ('ABT', 'Al-Baha'),
    ('HOF', 'Alahsa'),
    ('RAE', 'Arar'),
    ('BHH', 'Bisha'),
    ('DMM', 'Dammam'),
    ('DWD', 'Dawadmi'),
    ('DHA', 'Dhahran'),
    ('ELQ', 'Gassim'),
    ('URY', 'Gurayat'),
    ('HBT', 'Hafr Albatin'),
    ('HAS', 'Hail'),
    ('GIZ', 'Jazan'),
    ('JED', 'Jeddah'),
    ('AJF', 'Jouf'),
    ('KMX', 'Khamis Mushait'),
    ('MJH', 'Majma'),
    ('EAM', 'Nejran'),
    ('AQI', 'Qaisumah'),
    ('RAH', 'Rafha'),
    ('RUH', 'Riyadh'),
    ('SHW', 'Sharurah'),
    ('SLF', 'Sulayel'),
    ('TUU', 'Tabuk'),
    ('TIF', 'Taif'),
    ('TUI', 'Turaif'),
    ('UZH', 'Unayzah'),
    ('WAE', 'Wadi Ad Dawasir'),
    ('EJH', 'Wedjh'),
    ('YNB', 'Yanbu'),
    ('ZUL', 'Zilfi'),
]